export const INPUT_CITY_REQUEST = 'INPUT_CITY_REQUEST';
export const INPUT_CITY_SUCCESS = 'INPUT_CITY_SUCCESS';
export const INPUT_CITY_FAILURE = 'INPUT_CITY_FAILURE';

export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST';
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS';
export const GET_CITIES_FAILURE = 'GET_CITIES_FAILURE';

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_FAILURE = 'DELETE_CITY_FAILURE';


export const GET_DEFAULT_WEATHER_REQUEST = 'GET_DEFAULT_WEATHER_REQUEST';
export const GET_DEFAULT_WEATHER_SUCCESS = 'GET_DEFAULT_WEATHER_SUCCESS';
export const GET_DEFAULT_WEATHER_FAILURE = 'GET_DEFAULT_WEATHER_FAILURE';

export const GET_WEATHER_SENSOR_REQUEST = 'GET_WEATHER_SENSOR_REQUEST';
export const GET_WEATHER_SENSOR_SUCCESS = 'GET_WEATHER_SENSOR_SUCCESS';
export const GET_WEATHER_SENSOR_FAILURE = 'GET_WEATHER_SENSOR_FAILURE';
